[package]
name = "keywitch_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
log = "0.4.19"
scrypt = { version = "0.11.0", default-features = false }
serde = "1.0.183"
serde_json = "1.0.105"
